//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Rudder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionCodes
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
